FROM node:20-alpine AS base
RUN npm install -g pnpm@9
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY dist ./dist
COPY node_modules ./node_modules
EXPOSE 3005
CMD ["node", "dist/index.js"]
